// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATa3lLiqwn0fEvhuZR2cRPcpbBTKIQACI',
    appId: '1:698227374686:web:1f81120577951bdc0cd2cf',
    messagingSenderId: '698227374686',
    projectId: 'shopping-list-app-dev',
    authDomain: 'shopping-list-app-dev.firebaseapp.com',
    storageBucket: 'shopping-list-app-dev.appspot.com',
    measurementId: 'G-1LH76T44NV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY9q_ARFoNRN-mUy7SimojiOitoo1H1S0',
    appId: '1:698227374686:android:9fe935ad42be4fdf0cd2cf',
    messagingSenderId: '698227374686',
    projectId: 'shopping-list-app-dev',
    storageBucket: 'shopping-list-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB70_8vR1-g7f_9sYII50dY8-eF872qpo',
    appId: '1:698227374686:ios:0c7e763661d638050cd2cf',
    messagingSenderId: '698227374686',
    projectId: 'shopping-list-app-dev',
    storageBucket: 'shopping-list-app-dev.appspot.com',
    iosClientId: '698227374686-op2i3kqjb88gj3utkgrjb427nbqp7cdd.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB70_8vR1-g7f_9sYII50dY8-eF872qpo',
    appId: '1:698227374686:ios:0c7e763661d638050cd2cf',
    messagingSenderId: '698227374686',
    projectId: 'shopping-list-app-dev',
    storageBucket: 'shopping-list-app-dev.appspot.com',
    iosClientId: '698227374686-op2i3kqjb88gj3utkgrjb427nbqp7cdd.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingList',
  );
}
